const seedIdeas=[
 {p:'TikTok',a:'@mama.v.teme',title:'Когда подросток сказал «я сейчас»',views:932000,likes:88400,er:9.5,trend:98,emoji:'🙄',cover:'linear-gradient(145deg,#ffba7a,#ef6d80)'},
 {p:'Instagram',a:'@family.notes',title:'Мама пытается понять молодёжный сленг',views:714000,likes:67200,er:9.4,trend:95,emoji:'🤔',cover:'linear-gradient(145deg,#9dd9ff,#7775e8)'},
 {p:'TikTok',a:'@daughter_mode',title:'POV: попросили убрать комнату',views:548000,likes:51100,er:9.3,trend:91,emoji:'🧹',cover:'linear-gradient(145deg,#b8e986,#42b883)'},
 {p:'Instagram',a:'@two.generations',title:'Как мы выбираем семейный фильм',views:421000,likes:35200,er:8.4,trend:89,emoji:'🍿',cover:'linear-gradient(145deg,#f7b5d7,#a466d6)'},
 {p:'TikTok',a:'@mama_online',title:'Звонок от мамы: ожидание и реальность',views:386000,likes:33900,er:8.8,trend:87,emoji:'📱',cover:'linear-gradient(145deg,#ffd86f,#fc6262)'},
 {p:'Instagram',a:'@home.comedy',title:'Когда гости уже у двери',views:302000,likes:24100,er:8.0,trend:82,emoji:'🫣',cover:'linear-gradient(145deg,#83eaf1,#63a4ff)'},
 {p:'TikTok',a:'@mood.family',title:'Мама нашла старые фотографии',views:284000,likes:26700,er:9.4,trend:80,emoji:'📸',cover:'linear-gradient(145deg,#fbc2eb,#a6c1ee)'},
 {p:'Instagram',a:'@real.motherhood',title:'Три стадии сборов в школу',views:245000,likes:18300,er:7.5,trend:76,emoji:'🎒',cover:'linear-gradient(145deg,#fccb90,#d57eeb)'},
 {p:'TikTok',a:'@teen.translator',title:'Переводим ответы подростка на русский',views:198000,likes:21100,er:10.7,trend:75,emoji:'💬',cover:'linear-gradient(145deg,#84fab0,#8fd3f4)'},
 {p:'Instagram',a:'@our.days',title:'Один день глазами мамы и дочки',views:172000,likes:13400,er:7.8,trend:70,emoji:'👀',cover:'linear-gradient(145deg,#fa709a,#fee140)'},
 {p:'TikTok',a:'@family.script',title:'Кто съел вкусное из холодильника?',views:147000,likes:12600,er:8.6,trend:68,emoji:'🍰',cover:'linear-gradient(145deg,#30cfd0,#330867)'},
 {p:'Instagram',a:'@mother.said',title:'Фразы мамы, которые мы повторяем',views:119000,likes:9200,er:7.7,trend:64,emoji:'😂',cover:'linear-gradient(145deg,#e0c3fc,#8ec5fc)'}
];
const customIdeas=JSON.parse(localStorage.getItem('pulse-custom')||'[]');
const ideas=[...seedIdeas,...customIdeas];
ideas.forEach((idea,id)=>idea.id=id);
const state={saved:new Set(JSON.parse(localStorage.getItem('pulse-saved')||'[]')),query:'',sort:'trend',min:0,view:'search',collections:JSON.parse(localStorage.getItem('pulse-collections')||'[{"name":"На этой неделе","description":"Быстрые идеи для ближайших публикаций","color":"#dfff63"},{"name":"Семейные скетчи","description":"Сценарии с мамой и дочкой","color":"#b9aaff"}]'),plan:JSON.parse(localStorage.getItem('pulse-plan')||'[]')};
const $=s=>document.querySelector(s); const fmt=n=>n>=1e6?(n/1e6).toFixed(1)+'M':Math.round(n/1000)+'K';
const escapeHtml=value=>String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
state.youtubeKey=localStorage.getItem('pulse-youtube-key')||'';state.realResults=[];
function updateConnection(){const connected=Boolean(state.youtubeKey);$('#connectionStatus').textContent=connected?'YouTube подключён · результаты настоящие':'YouTube API не подключён';document.querySelector('.live-source').classList.toggle('connected',connected);$('#youtubeKeyInput').value=state.youtubeKey}
function renderLiveLanding(){$('#cards').innerHTML=`<div class="real-empty"><div class="empty-icon">▶</div><h3>${state.youtubeKey?'Введите тему для поиска':'Подключите YouTube API'}</h3><p>${state.youtubeKey?'Здесь появятся настоящие видео и Shorts с YouTube: их можно будет воспроизвести прямо в карточках.':'Без официального ключа сайт не может честно получать результаты YouTube. Подключение бесплатное в пределах квоты Google.'}</p><button id="emptyConnect">${state.youtubeKey?'Искать реальные видео':'Подключить API'}</button></div>`;$('#resultCount').textContent='0';$('#emptyConnect').onclick=()=>state.youtubeKey?$('#searchInput').focus():$('#apiDialog').showModal()}
async function searchYoutube(query){if(!state.youtubeKey){$('#apiDialog').showModal();return}$('#cards').innerHTML='<div class="search-loading">Ищу настоящие видео на YouTube…</div>';try{const params=new URLSearchParams({part:'snippet',type:'video',q:query,maxResults:'12',order:state.sort==='views'?'viewCount':'relevance',videoDuration:'short',videoEmbeddable:'true',relevanceLanguage:'ru',regionCode:'RU',key:state.youtubeKey}),searchResponse=await fetch(`https://www.googleapis.com/youtube/v3/search?${params}`),searchData=await searchResponse.json();if(!searchResponse.ok)throw new Error(searchData.error?.message||'YouTube API вернул ошибку');const ids=searchData.items.map(x=>x.id.videoId).join(','),statsResponse=await fetch(`https://www.googleapis.com/youtube/v3/videos?part=statistics,contentDetails&id=${ids}&key=${encodeURIComponent(state.youtubeKey)}`),statsData=await statsResponse.json(),statsMap=new Map((statsData.items||[]).map(x=>[x.id,x]));state.realResults=searchData.items.map(item=>({id:item.id.videoId,title:item.snippet.title,channel:item.snippet.channelTitle,published:item.snippet.publishedAt,thumbnail:item.snippet.thumbnails.high?.url||item.snippet.thumbnails.medium?.url,views:+(statsMap.get(item.id.videoId)?.statistics?.viewCount||0),likes:+(statsMap.get(item.id.videoId)?.statistics?.likeCount||0)}));renderYoutube()}catch(error){$('#cards').innerHTML=`<div class="api-error"><strong>Не удалось получить видео.</strong><br>${escapeHtml(error.message)}<br><br>Проверьте, включён ли YouTube Data API v3 и правильно ли настроены ограничения ключа.</div>`;$('#resultCount').textContent='0'}}
function renderYoutube(){const displayed=state.realResults.filter(x=>x.views>=state.min);$('#cards').innerHTML=displayed.map(x=>`<article class="card real-card"><div class="video-frame"><iframe src="https://www.youtube-nocookie.com/embed/${encodeURIComponent(x.id)}" title="${escapeHtml(x.title)}" loading="lazy" allow="accelerometer; autoplay; encrypted-media; picture-in-picture" allowfullscreen></iframe></div><div class="card-info"><h3>${escapeHtml(x.title)}</h3><p class="channel">${escapeHtml(x.channel)}</p><div class="metrics"><div class="metric"><strong>${fmt(x.views)}</strong><span>просмотры</span></div><div class="metric"><strong>${fmt(x.likes)}</strong><span>лайки</span></div><div class="metric"><strong>▶</strong><span>YouTube</span></div></div><a class="external-link" href="https://www.youtube.com/watch?v=${encodeURIComponent(x.id)}" target="_blank" rel="noreferrer">Открыть на YouTube ↗</a></div></article>`).join('')||'<div class="real-empty"><h3>Видео не найдены</h3><p>Попробуйте изменить запрос или снизить фильтр просмотров.</p></div>';$('#resultCount').textContent=displayed.length}
function visibleIdeas(){const platforms=[...document.querySelectorAll('.platforms input:checked')].map(x=>x.value);return ideas.filter(x=>platforms.includes(x.p)&&x.views>=state.min).sort((a,b)=>b[state.sort]-a[state.sort]);}
function render(list=visibleIdeas()){$('#cards').innerHTML=list.map((x,i)=>`<article class="card"><div class="cover" style="--cover:${x.cover};--rotate:${i%2?'5deg':'-5deg'}"><span class="badge">${x.p==='TikTok'?'♪':'◎'} ${x.p}</span><button class="save ${state.saved.has(x.id)?'saved':''}" data-id="${x.id}" aria-label="Сохранить">${state.saved.has(x.id)?'♥':'♡'}</button><div class="cover-art">${x.emoji}</div><h3>${x.title}</h3></div><div class="card-info"><div class="author"><strong>${x.a}</strong><span class="trend">↗ ${x.trend}% тренд</span></div><div class="metrics"><div class="metric"><strong>${fmt(x.views)}</strong><span>просмотры</span></div><div class="metric"><strong>${fmt(x.likes)}</strong><span>реакции</span></div><div class="metric"><strong>${x.er}%</strong><span>вовлечение</span></div></div><button class="breakdown" data-detail="${x.id}">Разобрать идею →</button></div></article>`).join('');$('#resultCount').textContent=list.length;$('#savedCount').textContent=state.saved.size;$('#planCount').textContent=state.plan.length;document.querySelectorAll('.save').forEach(b=>b.onclick=()=>toggleSave(+b.dataset.id));document.querySelectorAll('[data-detail]').forEach(b=>b.onclick=()=>showDetail(+b.dataset.detail));}
function toggleSave(id){state.saved.has(id)?state.saved.delete(id):state.saved.add(id);localStorage.setItem('pulse-saved',JSON.stringify([...state.saved]));state.view==='saved'?showSaved():render();showToast(state.saved.has(id)?'Сохранено в подборку':'Удалено из подборки');}
function showToast(text){const t=$('#toast');t.textContent=text;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
$('#searchForm').onsubmit=async e=>{e.preventDefault();state.query=$('#searchInput').value.trim();if(!state.query){showToast('Введите тему для поиска');return}await searchYoutube(state.query)};
document.querySelectorAll('.quick button').forEach(b=>b.onclick=()=>{$('#searchInput').value=b.textContent;$('#searchForm').requestSubmit()});
document.querySelectorAll('.platforms input').forEach(x=>x.onchange=()=>renderLiveLanding());
$('#sortSelect').onchange=e=>{state.sort=e.target.value;if(state.query&&state.youtubeKey)searchYoutube(state.query)};
$('#filterButton').onclick=()=>$('#filterDrawer').classList.toggle('open');
$('#minViews').oninput=e=>{state.min=+e.target.value;$('#minViewsLabel').textContent=state.min?fmt(state.min):'0';state.realResults.length?renderYoutube():renderLiveLanding()};
$('#themeButton').onclick=()=>document.body.classList.toggle('dark');
document.querySelectorAll('.nav-item').forEach(btn=>btn.onclick=()=>{document.querySelectorAll('.nav-item').forEach(x=>x.classList.remove('active'));btn.classList.add('active');const v=btn.dataset.view;if(v==='search')showSearch();else if(v==='saved')showSaved();else if(v==='collections')showCollections();else if(v==='planner')showPlanner();else showAnalytics()});
function hideViews(){['#searchView','#emptyView','#collectionsView','#plannerView','#analyticsView'].forEach(id=>$(id).hidden=true)}
function showSearch(){state.view='search';hideViews();$('#searchView').hidden=false;$('#pageTitle').textContent='Поиск реальных видео';state.realResults.length?renderYoutube():renderLiveLanding()}
function showSaved(){state.view='saved';hideViews();$('#searchView').hidden=false;$('#pageTitle').textContent='Сохранённые идеи';render(ideas.filter(x=>state.saved.has(x.id)));$('#resultCount').textContent=state.saved.size}
function showCollections(){state.view='collections';hideViews();$('#collectionsView').hidden=false;$('#pageTitle').textContent='Коллекции';renderCollections()}
function saveCollections(){localStorage.setItem('pulse-collections',JSON.stringify(state.collections))}
function renderCollections(){const saved=ideas.filter(x=>state.saved.has(x.id));$('#collectionGrid').innerHTML=state.collections.map((c,i)=>`<article class="collection-card" style="--accent:${c.color}"><div class="collection-top"><span>▦</span><button data-delete-collection="${i}" aria-label="Удалить коллекцию">×</button></div><h3>${c.name}</h3><p>${c.description||'Без описания'}</p><div class="collection-preview">${saved.slice(i,i+3).map(x=>`<span style="background:${x.cover}">${x.emoji}</span>`).join('')||'<small>Сохраните идеи, чтобы наполнить коллекцию</small>'}</div><strong>${saved.length} идей</strong></article>`).join('');document.querySelectorAll('[data-delete-collection]').forEach(b=>b.onclick=()=>{state.collections.splice(+b.dataset.deleteCollection,1);saveCollections();renderCollections()})}
function savePlan(){localStorage.setItem('pulse-plan',JSON.stringify(state.plan));$('#planCount').textContent=state.plan.length}
function showPlanner(){state.view='planner';hideViews();$('#plannerView').hidden=false;$('#pageTitle').textContent='Контент-план';renderPlanner()}
function renderPlanner(){const days=['Пн','Вт','Ср','Чт','Пт','Сб','Вс'],today=new Date();$('#weekStrip').innerHTML=days.map((d,i)=>`<div class="${i===today.getDay()-1?'today':''}"><span>${d}</span><strong>${new Date(today.getFullYear(),today.getMonth(),today.getDate()-today.getDay()+1+i).getDate()}</strong></div>`).join('');const cols=[['idea','Идеи'],['script','Сценарий'],['shoot','Съёмка'],['ready','Готово']];$('#kanban').innerHTML=cols.map(([key,label])=>`<section class="kanban-col"><header><h3>${label}</h3><b>${state.plan.filter(x=>x.status===key).length}</b></header><div>${state.plan.filter(x=>x.status===key).map(item=>{const x=ideas.find(y=>y.id===item.ideaId);return x?`<article class="plan-card"><span>${x.p} · ${x.emoji}</span><h4>${x.title}</h4><small>${item.date||'Без даты'}</small><div><button data-move="${item.ideaId}">Следующий этап →</button><button data-remove-plan="${item.ideaId}">×</button></div></article>`:''}).join('')||'<p class="column-empty">Пока пусто</p>'}</div></section>`).join('');document.querySelectorAll('[data-move]').forEach(b=>b.onclick=()=>movePlan(+b.dataset.move));document.querySelectorAll('[data-remove-plan]').forEach(b=>b.onclick=()=>{state.plan=state.plan.filter(x=>x.ideaId!==+b.dataset.removePlan);savePlan();renderPlanner()})}
function addToPlan(id){if(!state.plan.some(x=>x.ideaId===id)){state.plan.push({ideaId:id,status:'idea',date:new Date().toLocaleDateString('ru-RU',{day:'2-digit',month:'short'})});savePlan();showToast('Добавлено в контент-план')}else showToast('Уже есть в плане')}
function movePlan(id){const order=['idea','script','shoot','ready'],item=state.plan.find(x=>x.ideaId===id);item.status=order[Math.min(order.indexOf(item.status)+1,3)];savePlan();renderPlanner()}
function showDetail(id){const x=ideas.find(y=>y.id===id),hooks=[`«${x.title} — знакомо?»`,`То, о чём мамы обычно молчат…`,`Досмотрите до реакции в конце`];$('#detailContent').innerHTML=`<div class="detail-hero" style="background:${x.cover}"><button class="close-button" id="closeDetail">×</button><span>${x.emoji}</span><div><small>${x.p} · ${x.a}</small><h2>${x.title}</h2></div></div><div class="detail-body"><p class="eyebrow">ГОТОВЫЙ РАЗБОР</p><h3>Почему идея может сработать</h3><p>Узнаваемая бытовая ситуация быстро вызывает эмоцию и мотивирует зрителя отправить ролик близкому человеку.</p><h3>Три варианта начала</h3><ol>${hooks.map(h=>`<li>${h}</li>`).join('')}</ol><h3>Мини-сценарий</h3><div class="script-box"><b>0–2 сек.</b><p>Крупный план и короткая фраза-зацепка.</p><b>3–9 сек.</b><p>Покажите конфликт или смешное недопонимание.</p><b>10–15 сек.</b><p>Неожиданная реакция и вопрос зрителю.</p></div><div class="detail-actions"><button class="ghost" id="copyScript">Копировать сценарий</button><button class="add-button" id="detailPlan">＋ В контент-план</button></div></div>`;$('#detailDialog').showModal();$('#closeDetail').onclick=()=>$('#detailDialog').close();$('#detailPlan').onclick=()=>addToPlan(id);$('#copyScript').onclick=async()=>{await navigator.clipboard.writeText(`${x.title}\n0–2 сек: зацепка\n3–9 сек: конфликт\n10–15 сек: реакция и вопрос`);showToast('Сценарий скопирован')}}
$('#planFromSavedButton').onclick=()=>{const next=ideas.find(x=>state.saved.has(x.id)&&!state.plan.some(p=>p.ideaId===x.id));next?addToPlan(next.id):showToast('Сначала сохраните новую идею')};
function showAnalytics(){state.view='analytics';hideViews();$('#analyticsView').hidden=false;$('#pageTitle').textContent='Аналитика контента';renderAnalytics()}
function renderAnalytics(){const saved=ideas.filter(x=>state.saved.has(x.id)),base=saved.length?saved:ideas,totalViews=base.reduce((s,x)=>s+x.views,0),avgEr=base.reduce((s,x)=>s+x.er,0)/base.length,best=[...base].sort((a,b)=>b.trend-a.trend)[0];$('#statsGrid').innerHTML=`<article><span>Всего идей</span><strong>${ideas.length}</strong><small>＋ ${customIdeas.length} ваших</small></article><article><span>Потенциал просмотров</span><strong>${fmt(totalViews)}</strong><small>по выбранным идеям</small></article><article><span>Среднее вовлечение</span><strong>${avgEr.toFixed(1)}%</strong><small class="trend">выше среднего</small></article><article><span>Лидер тренда</span><strong>${best.trend}%</strong><small>${best.p} · ${best.a}</small></article>`;const top=[...base].sort((a,b)=>b.views-a.views).slice(0,6),max=top[0]?.views||1;$('#barChart').innerHTML=top.map(x=>`<div class="bar-row"><span>${x.title.slice(0,28)}</span><div><i style="width:${x.views/max*100}%"></i></div><strong>${fmt(x.views)}</strong></div>`).join('');const counts=['TikTok','Instagram','YouTube'].map(p=>({p,n:ideas.filter(x=>x.p===p).length})),total=ideas.length;$('#donut').style.background=`conic-gradient(#7258ff 0 ${counts[0].n/total*100}%,#dfff63 0 ${(counts[0].n+counts[1].n)/total*100}%,#ff9f7a 0)`;$('#donutTotal').textContent=total;$('#platformLegend').innerHTML=counts.map((x,i)=>`<p><i class="legend-dot c${i}"></i><span>${x.p}</span><strong>${x.n}</strong></p>`).join('');$('#recommendationText').textContent=`Лучше всего сейчас выглядит формат «${best.title}». Возьмите его механику, но придумайте собственный сюжет и первые 2 секунды.`}
$('#addIdeaButton').onclick=()=>$('#ideaDialog').showModal();
$('#ideaForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.currentTarget),views=+f.get('views'),likes=+f.get('likes');customIdeas.push({p:f.get('platform'),a:f.get('author')||'@мой_аккаунт',title:f.get('title'),views,likes,er:views?+(likes/views*100).toFixed(1):0,trend:55,emoji:f.get('emoji'),cover:'linear-gradient(145deg,#ffd86f,#8b5cf6)'});localStorage.setItem('pulse-custom',JSON.stringify(customIdeas));location.reload()};
$('#newCollectionButton').onclick=()=>$('#collectionDialog').showModal();
$('#collectionForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.currentTarget),colors=['#dfff63','#b9aaff','#ffbd9d','#8fe1d1'];state.collections.push({name:f.get('name'),description:f.get('description'),color:colors[state.collections.length%colors.length]});saveCollections();$('#collectionDialog').close();e.currentTarget.reset();renderCollections();showToast('Коллекция создана')};
$('#exportButton').onclick=()=>{const blob=new Blob([JSON.stringify({ideas,saved:[...state.saved],collections:state.collections},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='pulse-data.json';a.click();URL.revokeObjectURL(a.href);showToast('Данные экспортированы')};
$('#apiSettingsButton').onclick=()=>$('#apiDialog').showModal();
$('#apiForm').onsubmit=e=>{e.preventDefault();const key=new FormData(e.currentTarget).get('youtubeKey').trim();if(!key){showToast('Вставьте API-ключ');return}state.youtubeKey=key;localStorage.setItem('pulse-youtube-key',key);$('#apiDialog').close();updateConnection();renderLiveLanding();showToast('YouTube подключён')};
$('#removeKeyButton').onclick=()=>{localStorage.removeItem('pulse-youtube-key');state.youtubeKey='';state.realResults=[];$('#apiDialog').close();updateConnection();renderLiveLanding();showToast('Ключ удалён')};
$('#backToSearch').onclick=()=>{document.querySelector('[data-view="search"]').click()};updateConnection();renderLiveLanding();
